<?php

declare(strict_types=1);

namespace App\Twig\Components\Molecules;

use App\Service\Essayist\EssayistZapClaimService;
use App\Util\NostrKeyUtil;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\UX\LiveComponent\Attribute\AsLiveComponent;
use Symfony\UX\LiveComponent\Attribute\LiveAction;
use Symfony\UX\LiveComponent\Attribute\LiveArg;
use Symfony\UX\LiveComponent\Attribute\LiveProp;
use Symfony\UX\LiveComponent\DefaultActionTrait;

/**
 * Twig Live Component for claiming/verifying Essayist membership zaps.
 *
 * Allows members to paste their zap receipt event ID or BOLT11 invoice to claim membership.
 */
#[AsLiveComponent('Essayist:ClaimZap')]
final class EssayistClaimZapButton extends AbstractController
{
    use DefaultActionTrait;

    #[LiveProp(writable: true)]
    public string $sponsorNpub = ''; // The member pubkey who received the zap

    #[LiveProp(writable: true)]
    public string $phase = 'form'; // form | submitting | success | error

    /** The BOLT11 invoice used to make the payment (generated by the ZapButton). */
    #[LiveProp(writable: true)]
    public string $bolt11Invoice = '';

    /** The payment preimage received from the Lightning wallet after payment completed. */
    #[LiveProp(writable: true)]
    public string $paymentPreimage = '';

    /** Fallback: zap receipt event ID (kind 9735) if preimage is not available. */
    #[LiveProp(writable: true)]
    public string $zapReceiptEventId = '';

    #[LiveProp(writable: true)]
    public int $claimedAmountSats = 0;

    #[LiveProp(writable: true)]
    public string $errorMessage = '';

    #[LiveProp(writable: true)]
    public string $successMessage = '';

    #[LiveProp(writable: true)]
    public bool $claimVerified = false;

    public function __construct(
        private readonly EssayistZapClaimService $claimService,
    ) {
    }

    /**
     * Submit a zap claim.
     */
    #[LiveAction]
    public function submitClaim(): void
    {
        $this->phase = 'submitting';
        $this->errorMessage = '';
        $this->successMessage = '';

        $user = $this->getUser();
        if (!$user instanceof \App\Entity\User) {
            $this->phase = 'error';
            $this->errorMessage = 'You must be logged in to claim a zap.';
            return;
        }

        // Require at least one proof
        if (!$this->paymentPreimage && !$this->bolt11Invoice && !$this->zapReceiptEventId) {
            $this->phase = 'error';
            $this->errorMessage = 'Please provide a payment preimage, BOLT11 invoice, or zap receipt event ID.';
            return;
        }

        // If preimage is provided, bolt11 is required for verification
        if ($this->paymentPreimage && !$this->bolt11Invoice) {
            $this->phase = 'error';
            $this->errorMessage = 'To use a payment preimage, the BOLT11 invoice is also required.';
            return;
        }

        if (!$this->sponsorNpub) {
            $this->phase = 'error';
            $this->errorMessage = 'Sponsor pubkey is missing.';
            return;
        }

        try {
            $payerNpub = $user->getNpub();
            if (!$payerNpub) {
                $this->phase = 'error';
                $this->errorMessage = 'Your account is not linked to a Nostr pubkey.';
                return;
            }

            $payerHex   = NostrKeyUtil::npubToHex($payerNpub);
            $sponsorHex = NostrKeyUtil::npubToHex($this->sponsorNpub);

            $claim = $this->claimService->createClaim(
                user: $user,
                payerPubkeyHex: $payerHex,
                sponsorPubkeyHex: $sponsorHex,
                zapReceiptEventId: $this->zapReceiptEventId ?: null,
                bolt11Invoice: $this->bolt11Invoice ?: null,
                paymentPreimage: $this->paymentPreimage ?: null,
                claimedAmountSats: $this->claimedAmountSats > 0 ? $this->claimedAmountSats : null,
            );

            $verified = $this->claimService->verifyClaim($claim);

            if ($claim->isRejected()) {
                $this->phase = 'error';
                $this->errorMessage = $claim->getRejectionReason() ?? 'Claim verification failed.';
                return;
            }

            if ($verified) {
                $this->phase = 'success';
                $this->claimVerified = true;
                $this->successMessage = 'Your payment has been verified and your membership has been extended!';
            } else {
                $this->phase = 'success';
                $this->claimVerified = false;
                $this->successMessage = 'Your claim has been submitted. The recipient can confirm it from their members page (or admin can review it).';
            }

            $this->zapReceiptEventId = '';
            $this->bolt11Invoice = '';
            $this->paymentPreimage = '';
            $this->claimedAmountSats = 0;
        } catch (\Throwable $e) {
            $this->phase = 'error';
            $this->errorMessage = 'Error: ' . $e->getMessage();
        }
    }

    /**
     * Reset the form to initial state.
     */
    #[LiveAction]
    public function reset(): void
    {
        $this->phase = 'form';
        $this->zapReceiptEventId = '';
        $this->bolt11Invoice = '';
        $this->claimedAmountSats = 0;
        $this->errorMessage = '';
        $this->successMessage = '';
        $this->claimVerified = false;
    }
}




