<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Notifications Center: per-user notification subscriptions and delivered items.
 */
final class Version20260423120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Notifications Center: notification_subscription + notification tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE notification_subscription (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id INT NOT NULL,
                source_type VARCHAR(32) NOT NULL,
                source_value VARCHAR(512) NOT NULL,
                label VARCHAR(255) DEFAULT NULL,
                active BOOLEAN DEFAULT TRUE NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_notification_subscription ON notification_subscription (user_id, source_type, source_value)');
        $this->addSql('CREATE INDEX idx_notification_subscription_active_type ON notification_subscription (active, source_type)');
        $this->addSql('CREATE INDEX idx_notification_subscription_user ON notification_subscription (user_id)');
        $this->addSql('ALTER TABLE notification_subscription ADD CONSTRAINT fk_notification_subscription_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql(<<<'SQL'
            CREATE TABLE notification (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id INT NOT NULL,
                subscription_id INT DEFAULT NULL,
                event_id VARCHAR(64) NOT NULL,
                event_kind INT NOT NULL,
                event_pubkey VARCHAR(64) NOT NULL,
                event_coordinate VARCHAR(512) DEFAULT NULL,
                title VARCHAR(512) DEFAULT NULL,
                summary VARCHAR(1024) DEFAULT NULL,
                url VARCHAR(1024) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                seen_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_notification_user_event ON notification (user_id, event_id)');
        $this->addSql('CREATE INDEX idx_notification_user_unread ON notification (user_id, read_at)');
        $this->addSql('CREATE INDEX idx_notification_user_created ON notification (user_id, created_at)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT fk_notification_subscription FOREIGN KEY (subscription_id) REFERENCES notification_subscription (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE notification_subscription');
    }
}

