<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260324120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create hidden_coordinate table for hiding magazines from public listings';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE hidden_coordinate (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                coordinate VARCHAR(512) NOT NULL,
                reason VARCHAR(255) DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_hidden_coordinate ON hidden_coordinate (coordinate)
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN hidden_coordinate.created_at IS '(DC2Type:datetime_immutable)'
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            DROP TABLE hidden_coordinate
        SQL);
    }
}

