<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260217163142 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE publication_subdomain_subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, npub VARCHAR(255) NOT NULL, subdomain VARCHAR(255) NOT NULL, magazine_coordinate VARCHAR(500) NOT NULL, status VARCHAR(20) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, pending_invoice_bolt11 TEXT DEFAULT NULL, payment_event_id VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2E897958C1D5962E ON publication_subdomain_subscription (subdomain)');
        $this->addSql('CREATE INDEX idx_pub_subdomain_npub ON publication_subdomain_subscription (npub)');
        $this->addSql('CREATE INDEX idx_pub_subdomain_name ON publication_subdomain_subscription (subdomain)');
        $this->addSql('CREATE INDEX idx_pub_subdomain_status ON publication_subdomain_subscription (status)');
        $this->addSql('CREATE INDEX idx_pub_subdomain_expires ON publication_subdomain_subscription (expires_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE publication_subdomain_subscription');
    }
}
