<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260208140123 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE vanity_name (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, vanity_name VARCHAR(255) NOT NULL, npub VARCHAR(255) NOT NULL, pubkey_hex VARCHAR(64) NOT NULL, status VARCHAR(20) NOT NULL, payment_type VARCHAR(20) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, relays JSON DEFAULT NULL, pending_invoice_bolt11 TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E91EF685E91EF685 ON vanity_name (vanity_name)');
        $this->addSql('CREATE INDEX idx_vanity_name ON vanity_name (vanity_name)');
        $this->addSql('CREATE INDEX idx_vanity_npub ON vanity_name (npub)');
        $this->addSql('CREATE INDEX idx_vanity_pubkey ON vanity_name (pubkey_hex)');
        $this->addSql('CREATE INDEX idx_vanity_status ON vanity_name (status)');
        $this->addSql('ALTER TABLE rememberme_token ALTER class SET DEFAULT \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE vanity_name');
        $this->addSql('ALTER TABLE rememberme_token ALTER class DROP DEFAULT');
    }
}
