<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260112155957 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE article ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN unfold_site.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN unfold_site.updated_at IS \'\'');
        $this->addSql('ALTER INDEX uniq_unfold_site_subdomain RENAME TO UNIQ_2059D498C1D5962E');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE article ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN unfold_site.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN unfold_site.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX uniq_2059d498c1d5962e RENAME TO uniq_unfold_site_subdomain');
    }
}
