<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260312140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create user_upload table to persist URLs of files uploaded by users';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE user_upload (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                npub VARCHAR(255) NOT NULL,
                url VARCHAR(1024) NOT NULL,
                provider VARCHAR(64) NOT NULL,
                mime_type VARCHAR(128) DEFAULT NULL,
                original_filename VARCHAR(512) DEFAULT NULL,
                file_size INT DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('COMMENT ON COLUMN user_upload.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX idx_user_upload_npub ON user_upload (npub)');
        $this->addSql('CREATE INDEX idx_user_upload_created ON user_upload (npub, created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE user_upload');
    }
}

