<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260124121229 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add indexes for profile event queries (kind+pubkey+created_at for efficient profile projection updates)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX idx_event_kind');
        $this->addSql('DROP INDEX idx_magazine_pubkey');

        // Add composite index for efficient profile event queries
        // This supports: SELECT * FROM event WHERE pubkey = ? AND kind IN (0, 10002) ORDER BY created_at DESC
        $this->addSql('CREATE INDEX idx_event_pubkey_kind_created ON event (pubkey, kind, created_at DESC)');

        $this->addSql('ALTER TABLE magazine ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE magazine ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE magazine ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE magazine ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER INDEX magazine_slug_key RENAME TO UNIQ_378C2FE4989D9B62');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE INDEX idx_event_kind ON event (kind)');

        // Drop the composite index added in up()
        $this->addSql('DROP INDEX idx_event_pubkey_kind_created');

        $this->addSql('ALTER TABLE magazine ALTER id SET DEFAULT nextval(\'magazine_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE magazine ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE magazine ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE magazine ALTER updated_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('CREATE INDEX idx_magazine_pubkey ON magazine (pubkey)');
        $this->addSql('ALTER INDEX uniq_378c2fe4989d9b62 RENAME TO magazine_slug_key');
    }
}
