<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260914160827 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE chat_community_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE chat_user_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE chat_community_membership_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE chat_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE chat_group_membership_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE chat_invite_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE chat_session_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE chat_push_subscription_id_seq CASCADE');
        $this->addSql('ALTER TABLE chat_community_membership DROP CONSTRAINT chat_community_membership_user_id_fkey');
        $this->addSql('ALTER TABLE chat_community_membership DROP CONSTRAINT chat_community_membership_community_id_fkey');
        $this->addSql('ALTER TABLE chat_group DROP CONSTRAINT chat_group_community_id_fkey');
        $this->addSql('ALTER TABLE chat_group_membership DROP CONSTRAINT chat_group_membership_group_id_fkey');
        $this->addSql('ALTER TABLE chat_group_membership DROP CONSTRAINT chat_group_membership_user_id_fkey');
        $this->addSql('ALTER TABLE chat_invite DROP CONSTRAINT chat_invite_community_id_fkey');
        $this->addSql('ALTER TABLE chat_invite DROP CONSTRAINT chat_invite_group_id_fkey');
        $this->addSql('ALTER TABLE chat_invite DROP CONSTRAINT chat_invite_created_by_id_fkey');
        $this->addSql('ALTER TABLE chat_push_subscription DROP CONSTRAINT fk_chat_push_user');
        $this->addSql('ALTER TABLE chat_session DROP CONSTRAINT chat_session_user_id_fkey');
        $this->addSql('ALTER TABLE chat_session DROP CONSTRAINT chat_session_community_id_fkey');
        $this->addSql('ALTER TABLE chat_user DROP CONSTRAINT chat_user_community_id_fkey');
        $this->addSql('ALTER TABLE chat_user DROP CONSTRAINT fk_chat_user_main_app_user');
        $this->addSql('DROP TABLE chat_community');
        $this->addSql('DROP TABLE chat_community_membership');
        $this->addSql('DROP TABLE chat_group');
        $this->addSql('DROP TABLE chat_group_membership');
        $this->addSql('DROP TABLE chat_invite');
        $this->addSql('DROP TABLE chat_push_subscription');
        $this->addSql('DROP TABLE chat_session');
        $this->addSql('DROP TABLE chat_user');
        $this->addSql('DROP TABLE credit_transaction');
        $this->addSql('ALTER INDEX uniq_app_user_local_identifier RENAME TO UNIQ_88BDF3E9150DD93A');
        $this->addSql('DROP INDEX idx_article_essayist_exclusive');
        $this->addSql('ALTER TABLE article_in_publication ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE article_in_publication ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE article_in_publication ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE essayist_membership ALTER amount_sats DROP DEFAULT');
        $this->addSql('ALTER INDEX uniq_essayist_membership_receipt RENAME TO UNIQ_F0039A58A9CB179B');
        $this->addSql('DROP INDEX idx_essayist_zap_claim_receipt_id');
        $this->addSql('DROP INDEX idx_essayist_zap_claim_bolt11');
        $this->addSql('ALTER TABLE essayist_zap_claim ALTER status DROP DEFAULT');
        $this->addSql('DROP INDEX idx_event_tags_gin');
        $this->addSql('ALTER TABLE identity_user_link ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE identity_user_link ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE monitored_relay ALTER id TYPE INT');
        $this->addSql('ALTER TABLE monitored_relay ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE monitored_relay ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE monitored_relay ALTER monitor_pubkey TYPE VARCHAR(64)');
        $this->addSql('ALTER TABLE monitored_relay ALTER event_id TYPE VARCHAR(64)');
        $this->addSql('ALTER TABLE relay_information ALTER pubkey TYPE VARCHAR(64)');
        $this->addSql('ALTER TABLE relay_monitor ALTER pubkey TYPE VARCHAR(64)');
        $this->addSql('ALTER TABLE relay_monitor ALTER event_id TYPE VARCHAR(64)');
        $this->addSql('ALTER TABLE trusted_relay_monitor ALTER pubkey TYPE VARCHAR(64)');
        $this->addSql('ALTER TABLE trusted_relay_monitor ALTER trusted_at DROP DEFAULT');
        $this->addSql('DROP INDEX idx_visit_is_bot');
        $this->addSql('DROP INDEX idx_visit_is_bot_visited_at');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE chat_community_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE chat_user_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE chat_community_membership_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE chat_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE chat_group_membership_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE chat_invite_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE chat_session_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE chat_push_subscription_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE chat_community (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, subdomain VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, status VARCHAR(20) NOT NULL, relay_url VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_3d8d5248c1d5962e ON chat_community (subdomain)');
        $this->addSql('CREATE TABLE chat_community_membership (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, community_id INT NOT NULL, role VARCHAR(20) NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX chat_cm_user_community ON chat_community_membership (user_id, community_id)');
        $this->addSql('CREATE INDEX IDX_BD0C2D96A76ED395 ON chat_community_membership (user_id)');
        $this->addSql('CREATE INDEX IDX_BD0C2D96FDA7B0BF ON chat_community_membership (community_id)');
        $this->addSql('CREATE TABLE chat_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, community_id INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, channel_event_id VARCHAR(64) DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX chat_group_community_slug ON chat_group (community_id, slug)');
        $this->addSql('CREATE INDEX IDX_6CBDA95EFDA7B0BF ON chat_group (community_id)');
        $this->addSql('CREATE TABLE chat_group_membership (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, group_id INT NOT NULL, role VARCHAR(20) NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, muted_notifications BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX chat_gm_user_group ON chat_group_membership (user_id, group_id)');
        $this->addSql('CREATE INDEX IDX_A45E67FAFE54D947 ON chat_group_membership (group_id)');
        $this->addSql('CREATE INDEX IDX_A45E67FAA76ED395 ON chat_group_membership (user_id)');
        $this->addSql('CREATE TABLE chat_invite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, community_id INT NOT NULL, group_id INT DEFAULT NULL, token_hash VARCHAR(64) NOT NULL, type VARCHAR(20) NOT NULL, role_to_grant VARCHAR(20) NOT NULL, created_by_id INT NOT NULL, max_uses INT DEFAULT NULL, used_count INT NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX chat_invite_token_hash ON chat_invite (token_hash)');
        $this->addSql('CREATE INDEX IDX_A03E27F6FDA7B0BF ON chat_invite (community_id)');
        $this->addSql('CREATE INDEX IDX_A03E27F6FE54D947 ON chat_invite (group_id)');
        $this->addSql('CREATE INDEX IDX_A03E27F6B03A8386 ON chat_invite (created_by_id)');
        $this->addSql('CREATE TABLE chat_push_subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, chat_user_id INT NOT NULL, endpoint TEXT NOT NULL, public_key VARCHAR(255) NOT NULL, auth_token VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_b308e22aeb601ffc ON chat_push_subscription (chat_user_id)');
        $this->addSql('CREATE UNIQUE INDEX chat_push_endpoint_unique ON chat_push_subscription (endpoint)');
        $this->addSql('CREATE TABLE chat_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, community_id INT NOT NULL, session_token VARCHAR(128) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX chat_session_token ON chat_session (session_token)');
        $this->addSql('CREATE INDEX IDX_9C4A19BDA76ED395 ON chat_session (user_id)');
        $this->addSql('CREATE INDEX IDX_9C4A19BDFDA7B0BF ON chat_session (community_id)');
        $this->addSql('CREATE TABLE chat_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, community_id INT NOT NULL, display_name VARCHAR(255) NOT NULL, about TEXT DEFAULT NULL, pubkey VARCHAR(64) NOT NULL, encrypted_private_key TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, activated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, main_app_user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_2b0f4b089eb09b4e ON chat_user (main_app_user_id)');
        $this->addSql('CREATE UNIQUE INDEX chat_user_community_pubkey ON chat_user (community_id, pubkey)');
        $this->addSql('CREATE UNIQUE INDEX chat_user_community_main_user ON chat_user (community_id, main_app_user_id)');
        $this->addSql('CREATE INDEX IDX_2B0F4B08FDA7B0BF ON chat_user (community_id)');
        $this->addSql('CREATE TABLE credit_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, npub VARCHAR(64) NOT NULL, amount INT NOT NULL, type VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reason VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE chat_community_membership ADD CONSTRAINT chat_community_membership_user_id_fkey FOREIGN KEY (user_id) REFERENCES chat_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chat_community_membership ADD CONSTRAINT chat_community_membership_community_id_fkey FOREIGN KEY (community_id) REFERENCES chat_community (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chat_group ADD CONSTRAINT chat_group_community_id_fkey FOREIGN KEY (community_id) REFERENCES chat_community (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chat_group_membership ADD CONSTRAINT chat_group_membership_group_id_fkey FOREIGN KEY (group_id) REFERENCES chat_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chat_group_membership ADD CONSTRAINT chat_group_membership_user_id_fkey FOREIGN KEY (user_id) REFERENCES chat_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chat_invite ADD CONSTRAINT chat_invite_community_id_fkey FOREIGN KEY (community_id) REFERENCES chat_community (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chat_invite ADD CONSTRAINT chat_invite_group_id_fkey FOREIGN KEY (group_id) REFERENCES chat_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chat_invite ADD CONSTRAINT chat_invite_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES chat_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chat_push_subscription ADD CONSTRAINT fk_chat_push_user FOREIGN KEY (chat_user_id) REFERENCES chat_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chat_session ADD CONSTRAINT chat_session_user_id_fkey FOREIGN KEY (user_id) REFERENCES chat_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chat_session ADD CONSTRAINT chat_session_community_id_fkey FOREIGN KEY (community_id) REFERENCES chat_community (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chat_user ADD CONSTRAINT chat_user_community_id_fkey FOREIGN KEY (community_id) REFERENCES chat_community (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chat_user ADD CONSTRAINT fk_chat_user_main_app_user FOREIGN KEY (main_app_user_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX uniq_88bdf3e9150dd93a RENAME TO uniq_app_user_local_identifier');
        $this->addSql('CREATE INDEX idx_article_essayist_exclusive ON article (essayist_exclusive) WHERE (essayist_exclusive = true)');
        $this->addSql('ALTER TABLE article_in_publication ALTER id SET DEFAULT nextval(\'article_in_publication_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE article_in_publication ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE article_in_publication ALTER updated_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE essayist_membership ALTER amount_sats SET DEFAULT 0');
        $this->addSql('ALTER INDEX uniq_f0039a58a9cb179b RENAME TO uniq_essayist_membership_receipt');
        $this->addSql('ALTER TABLE essayist_zap_claim ALTER status SET DEFAULT \'pending\'');
        $this->addSql('CREATE UNIQUE INDEX idx_essayist_zap_claim_receipt_id ON essayist_zap_claim (zap_receipt_event_id) WHERE (zap_receipt_event_id IS NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX idx_essayist_zap_claim_bolt11 ON essayist_zap_claim (bolt11_invoice) WHERE (bolt11_invoice IS NOT NULL)');
        $this->addSql('CREATE INDEX idx_event_tags_gin ON event (tags)');
        $this->addSql('ALTER TABLE identity_user_link ALTER id SET DEFAULT nextval(\'identity_user_link_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE identity_user_link ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE monitored_relay ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE monitored_relay ALTER id SET DEFAULT nextval(\'monitored_relay_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE monitored_relay ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE monitored_relay ALTER monitor_pubkey TYPE CHAR(64)');
        $this->addSql('ALTER TABLE monitored_relay ALTER event_id TYPE CHAR(64)');
        $this->addSql('ALTER TABLE relay_information ALTER pubkey TYPE CHAR(64)');
        $this->addSql('ALTER TABLE relay_monitor ALTER pubkey TYPE CHAR(64)');
        $this->addSql('ALTER TABLE relay_monitor ALTER event_id TYPE CHAR(64)');
        $this->addSql('ALTER TABLE trusted_relay_monitor ALTER pubkey TYPE CHAR(64)');
        $this->addSql('ALTER TABLE trusted_relay_monitor ALTER trusted_at SET DEFAULT \'now()\'');
        $this->addSql('CREATE INDEX idx_visit_is_bot ON visit (is_bot)');
        $this->addSql('CREATE INDEX idx_visit_is_bot_visited_at ON visit (is_bot, visited_at)');
    }
}
