<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260323161221 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE parsed_reference_id_seq CASCADE');
        $this->addSql('DROP TABLE current_record');
        $this->addSql('DROP TABLE parsed_reference');
        $this->addSql('COMMENT ON COLUMN app_user.last_metadata_refresh IS \'\'');
        $this->addSql('COMMENT ON COLUMN app_user.last_login_at IS \'\'');
        $this->addSql('ALTER TABLE chat_community ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE chat_community ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE chat_community ALTER status DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN chat_community.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN chat_community.updated_at IS \'\'');
        $this->addSql('ALTER INDEX uniq_chat_community_subdomain RENAME TO UNIQ_3D8D5248C1D5962E');
        $this->addSql('ALTER TABLE chat_community_membership ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE chat_community_membership ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE chat_community_membership ALTER role DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN chat_community_membership.joined_at IS \'\'');
        $this->addSql('ALTER TABLE chat_group ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE chat_group ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE chat_group ALTER status DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN chat_group.created_at IS \'\'');
        $this->addSql('ALTER TABLE chat_group_membership ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE chat_group_membership ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE chat_group_membership ALTER role DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN chat_group_membership.joined_at IS \'\'');
        $this->addSql('ALTER TABLE chat_invite ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE chat_invite ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE chat_invite ALTER type DROP DEFAULT');
        $this->addSql('ALTER TABLE chat_invite ALTER role_to_grant DROP DEFAULT');
        $this->addSql('ALTER TABLE chat_invite ALTER used_count DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN chat_invite.expires_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN chat_invite.revoked_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN chat_invite.created_at IS \'\'');
        $this->addSql('ALTER TABLE chat_push_subscription ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE chat_push_subscription ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN chat_push_subscription.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN chat_push_subscription.expires_at IS \'\'');
        $this->addSql('ALTER INDEX idx_chat_push_user RENAME TO IDX_B308E22AEB601FFC');
        $this->addSql('ALTER TABLE chat_session ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE chat_session ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN chat_session.expires_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN chat_session.revoked_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN chat_session.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN chat_session.last_seen_at IS \'\'');
        $this->addSql('DROP INDEX idx_chat_user_pubkey');
        $this->addSql('DROP INDEX chat_user_community_main_user');
        $this->addSql('ALTER TABLE chat_user ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE chat_user ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE chat_user ALTER status DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN chat_user.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN chat_user.activated_at IS \'\'');
        $this->addSql('CREATE UNIQUE INDEX chat_user_community_main_user ON chat_user (community_id, main_app_user_id)');
        $this->addSql('ALTER INDEX idx_chat_user_main_app_user RENAME TO IDX_2B0F4B089EB09B4E');
        $this->addSql('DROP INDEX idx_event_coord');
        $this->addSql('DROP INDEX idx_event_tags_gin');
        $this->addSql('ALTER TABLE follow_pack_source ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE follow_pack_source ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE follow_pack_source ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE follow_pack_source ALTER updated_at DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN follow_pack_source.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN follow_pack_source.updated_at IS \'\'');
        $this->addSql('ALTER INDEX follow_pack_source_purpose_key RENAME TO UNIQ_E2FF92CAB887B3EB');
        $this->addSql('ALTER TABLE media_asset_cache ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE media_asset_cache ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN user_upload.created_at IS \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE parsed_reference_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE current_record (record_uid VARCHAR(800) NOT NULL, coord VARCHAR(800) NOT NULL, kind INT NOT NULL, pubkey VARCHAR(255) NOT NULL, d_tag VARCHAR(512) DEFAULT NULL, current_event_id VARCHAR(225) NOT NULL, current_created_at BIGINT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT \'now()\' NOT NULL, PRIMARY KEY (record_uid))');
        $this->addSql('CREATE INDEX idx_current_record_pubkey ON current_record (pubkey)');
        $this->addSql('CREATE UNIQUE INDEX current_record_coord_key ON current_record (coord)');
        $this->addSql('CREATE INDEX idx_current_record_kind ON current_record (kind)');
        $this->addSql('CREATE TABLE parsed_reference (id INT DEFAULT nextval(\'parsed_reference_id_seq\'::regclass) NOT NULL, source_event_id VARCHAR(225) NOT NULL, tag_name VARCHAR(10) DEFAULT \'a\' NOT NULL, target_ref_type VARCHAR(20) DEFAULT \'coordinate\' NOT NULL, target_kind INT DEFAULT NULL, target_pubkey VARCHAR(255) DEFAULT NULL, target_d_tag VARCHAR(512) DEFAULT NULL, target_coord VARCHAR(800) DEFAULT NULL, relation VARCHAR(50) DEFAULT \'references\' NOT NULL, marker VARCHAR(255) DEFAULT NULL, "position" INT DEFAULT 0 NOT NULL, is_structural BOOLEAN DEFAULT false NOT NULL, is_resolvable BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_parsed_ref_target_parts ON parsed_reference (target_kind, target_pubkey, target_d_tag)');
        $this->addSql('CREATE INDEX idx_parsed_ref_source ON parsed_reference (source_event_id)');
        $this->addSql('CREATE INDEX idx_parsed_ref_target_coord ON parsed_reference (target_coord)');
        $this->addSql('COMMENT ON COLUMN app_user.last_metadata_refresh IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN app_user.last_login_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE chat_community ALTER id SET DEFAULT nextval(\'chat_community_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE chat_community ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE chat_community ALTER status SET DEFAULT \'active\'');
        $this->addSql('COMMENT ON COLUMN chat_community.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN chat_community.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX uniq_3d8d5248c1d5962e RENAME TO uniq_chat_community_subdomain');
        $this->addSql('ALTER TABLE chat_community_membership ALTER id SET DEFAULT nextval(\'chat_community_membership_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE chat_community_membership ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE chat_community_membership ALTER role SET DEFAULT \'user\'');
        $this->addSql('COMMENT ON COLUMN chat_community_membership.joined_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE chat_group ALTER id SET DEFAULT nextval(\'chat_group_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE chat_group ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE chat_group ALTER status SET DEFAULT \'active\'');
        $this->addSql('COMMENT ON COLUMN chat_group.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE chat_group_membership ALTER id SET DEFAULT nextval(\'chat_group_membership_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE chat_group_membership ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE chat_group_membership ALTER role SET DEFAULT \'member\'');
        $this->addSql('COMMENT ON COLUMN chat_group_membership.joined_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE chat_invite ALTER id SET DEFAULT nextval(\'chat_invite_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE chat_invite ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE chat_invite ALTER type SET DEFAULT \'activation\'');
        $this->addSql('ALTER TABLE chat_invite ALTER role_to_grant SET DEFAULT \'user\'');
        $this->addSql('ALTER TABLE chat_invite ALTER used_count SET DEFAULT 0');
        $this->addSql('COMMENT ON COLUMN chat_invite.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN chat_invite.revoked_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN chat_invite.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE chat_push_subscription ALTER id SET DEFAULT nextval(\'chat_push_subscription_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE chat_push_subscription ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN chat_push_subscription.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN chat_push_subscription.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_b308e22aeb601ffc RENAME TO idx_chat_push_user');
        $this->addSql('ALTER TABLE chat_session ALTER id SET DEFAULT nextval(\'chat_session_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE chat_session ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN chat_session.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN chat_session.revoked_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN chat_session.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN chat_session.last_seen_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('DROP INDEX chat_user_community_main_user');
        $this->addSql('ALTER TABLE chat_user ALTER id SET DEFAULT nextval(\'chat_user_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE chat_user ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE chat_user ALTER status SET DEFAULT \'pending\'');
        $this->addSql('COMMENT ON COLUMN chat_user.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN chat_user.activated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX idx_chat_user_pubkey ON chat_user (pubkey)');
        $this->addSql('CREATE UNIQUE INDEX chat_user_community_main_user ON chat_user (community_id, main_app_user_id) WHERE (main_app_user_id IS NOT NULL)');
        $this->addSql('ALTER INDEX idx_2b0f4b089eb09b4e RENAME TO idx_chat_user_main_app_user');
        $this->addSql('CREATE INDEX idx_event_coord ON event (kind, pubkey, d_tag) WHERE (d_tag IS NOT NULL)');
        $this->addSql('CREATE INDEX idx_event_tags_gin ON event (tags)');
        $this->addSql('ALTER TABLE follow_pack_source ALTER id SET DEFAULT nextval(\'follow_pack_source_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE follow_pack_source ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE follow_pack_source ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE follow_pack_source ALTER updated_at SET DEFAULT \'now()\'');
        $this->addSql('COMMENT ON COLUMN follow_pack_source.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN follow_pack_source.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX uniq_e2ff92cab887b3eb RENAME TO follow_pack_source_purpose_key');
        $this->addSql('ALTER TABLE media_asset_cache ALTER id SET DEFAULT nextval(\'media_asset_cache_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE media_asset_cache ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN user_upload.created_at IS \'(DC2Type:datetime_immutable)\'');
    }
}
