<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Notifications Pro paywall: dedicated subscription table modelled on
 * active_indexing_subscription but without relay-fetch configuration.
 */
final class Version20260423140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Notifications Pro subscription table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE notification_pro_subscription (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                npub VARCHAR(255) NOT NULL,
                tier VARCHAR(20) NOT NULL,
                status VARCHAR(20) NOT NULL,
                started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                grace_ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                pending_invoice_bolt11 TEXT DEFAULT NULL,
                zap_receipt_event_id VARCHAR(255) DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_notif_pro_npub ON notification_pro_subscription (npub)');
        $this->addSql('CREATE INDEX idx_notif_pro_npub ON notification_pro_subscription (npub)');
        $this->addSql('CREATE INDEX idx_notif_pro_status ON notification_pro_subscription (status)');
        $this->addSql('CREATE INDEX idx_notif_pro_expires ON notification_pro_subscription (expires_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE notification_pro_subscription');
    }
}

