<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * NIP-09: add deleted_event tombstone table so honored kind:5 deletion requests
 * suppress re-ingestion of the referenced events.
 */
final class Version20260422120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'NIP-09: deleted_event tombstone table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE deleted_event (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                target_ref VARCHAR(512) NOT NULL,
                ref_type VARCHAR(1) NOT NULL,
                pubkey VARCHAR(64) NOT NULL,
                kind INT DEFAULT NULL,
                deletion_event_id VARCHAR(64) NOT NULL,
                deletion_created_at BIGINT NOT NULL,
                reason TEXT DEFAULT NULL,
                recorded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_deleted_event_target_ref ON deleted_event (target_ref)');
        $this->addSql('CREATE INDEX idx_deleted_event_target_ref ON deleted_event (target_ref)');
        $this->addSql('CREATE INDEX idx_deleted_event_pubkey ON deleted_event (pubkey)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE deleted_event');
    }
}

