<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260424105529 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX idx_deleted_event_target_ref');
        $this->addSql('COMMENT ON COLUMN hidden_coordinate.created_at IS \'\'');
        $this->addSql('ALTER INDEX uniq_notif_pro_npub RENAME TO UNIQ_3BA3A8AB5FB8BABB');
        $this->addSql('ALTER TABLE user_relay_list ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE user_relay_list ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE user_relay_list ALTER read_relays DROP DEFAULT');
        $this->addSql('ALTER TABLE user_relay_list ALTER write_relays DROP DEFAULT');
        $this->addSql('ALTER TABLE user_relay_list ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE user_relay_list ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER INDEX uniq_user_relay_list_pubkey RENAME TO UNIQ_F9C2EE666F2C8EEE');
        $this->addSql('DROP INDEX idx_visit_subdomain');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE INDEX idx_deleted_event_target_ref ON deleted_event (target_ref)');
        $this->addSql('COMMENT ON COLUMN hidden_coordinate.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX uniq_3ba3a8ab5fb8babb RENAME TO uniq_notif_pro_npub');
        $this->addSql('ALTER TABLE user_relay_list ALTER id SET DEFAULT nextval(\'user_relay_list_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE user_relay_list ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE user_relay_list ALTER read_relays SET DEFAULT \'[]\'');
        $this->addSql('ALTER TABLE user_relay_list ALTER write_relays SET DEFAULT \'[]\'');
        $this->addSql('ALTER TABLE user_relay_list ALTER created_at SET DEFAULT 0');
        $this->addSql('ALTER TABLE user_relay_list ALTER updated_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER INDEX uniq_f9c2ee666f2c8eee RENAME TO uniq_user_relay_list_pubkey');
        $this->addSql('CREATE INDEX idx_visit_subdomain ON visit (subdomain)');
    }
}
