<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Essayist zap claim ledger — tracks pending zap claims waiting for verification.
 * Members can claim membership by providing a zap receipt event ID or BOLT11 invoice.
 */
final class Version20260603120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Essayist zap claim ledger for manual zap verification';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE essayist_zap_claim (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id INT NOT NULL,
                payer_pubkey VARCHAR(64) NOT NULL,
                sponsor_pubkey VARCHAR(64) NOT NULL,
                zap_receipt_event_id VARCHAR(64) DEFAULT NULL,
                bolt11_invoice VARCHAR(1024) DEFAULT NULL,
                payment_preimage VARCHAR(64) DEFAULT NULL,
                claimed_amount_sats INT DEFAULT NULL,
                status VARCHAR(32) NOT NULL DEFAULT 'pending',
                rejection_reason TEXT DEFAULT NULL,
                verification_method VARCHAR(32) DEFAULT NULL,
                recipient_attestor_pubkey VARCHAR(64) DEFAULT NULL,
                recipient_attestation_event_id VARCHAR(64) DEFAULT NULL,
                recipient_attestation_note TEXT DEFAULT NULL,
                created_at TIMESTAMP(0) NOT NULL,
                verified_at TIMESTAMP(0) DEFAULT NULL,
                CONSTRAINT fk_essayist_zap_claim_user_id FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE,
                PRIMARY KEY (id)
            )
        SQL
        );

        $this->addSql('CREATE INDEX idx_essayist_zap_claim_status ON essayist_zap_claim (status)');
        $this->addSql('CREATE INDEX idx_essayist_zap_claim_user ON essayist_zap_claim (user_id)');
        $this->addSql('CREATE INDEX idx_essayist_zap_claim_created_at ON essayist_zap_claim (created_at)');
        $this->addSql('CREATE UNIQUE INDEX idx_essayist_zap_claim_receipt_id ON essayist_zap_claim (zap_receipt_event_id) WHERE zap_receipt_event_id IS NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX idx_essayist_zap_claim_bolt11 ON essayist_zap_claim (bolt11_invoice) WHERE bolt11_invoice IS NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE essayist_zap_claim');
    }
}


