<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Essayist membership ledger — one row per kind:9735 zap receipt that
 * extends a user's Essayist membership window. The unique index on
 * `zap_receipt_event_id` provides replay protection so a single receipt
 * can never mint more than one grant.
 */
final class Version20260522120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Essayist membership ledger (zap-receipt-backed grants)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE essayist_membership (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id INT NOT NULL,
                payer_pubkey VARCHAR(64) NOT NULL,
                contributed_to_pubkey VARCHAR(64) NOT NULL,
                zap_receipt_event_id VARCHAR(64) NOT NULL,
                amount_sats INT NOT NULL DEFAULT 0,
                started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id),
                CONSTRAINT fk_essayist_membership_user FOREIGN KEY (user_id)
                    REFERENCES app_user (id) ON DELETE CASCADE
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_essayist_membership_receipt ON essayist_membership (zap_receipt_event_id)');
        $this->addSql('CREATE INDEX idx_essayist_membership_user ON essayist_membership (user_id)');
        $this->addSql('CREATE INDEX idx_essayist_membership_expires_at ON essayist_membership (expires_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE essayist_membership');
    }
}

