<?php

namespace App\Enum;

enum RolesEnum: string
{
    case USER = 'ROLE_USER';
    case ADMIN = 'ROLE_ADMIN';
    case EDITOR = 'ROLE_EDITOR';
    case WRITER = 'ROLE_WRITER';
    case FEATURED_WRITER = 'ROLE_FEATURED_WRITER';
    case MUTED = 'ROLE_MUTED';
    case ACTIVE_INDEXING = 'ROLE_ACTIVE_INDEXING';
    case UPDATES_PRO = 'ROLE_UPDATES_PRO';
    case RSS = 'ROLE_RSS';
    case ESSAYIST_CANDIDATE = 'ROLE_ESSAYIST_CANDIDATE';
    case ESSAYIST_AUTHOR = 'ROLE_ESSAYIST_AUTHOR';
    case ESSAYIST_SUPPORTER = 'ROLE_ESSAYIST_SUPPORTER';
    case ESSAYIST_MEMBER = 'ROLE_ESSAYIST_MEMBER';
    case ESSAYIST_EARLY_BIRD = 'ROLE_ESSAYIST_EARLY_BIRD';
}
