services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $kernelCacheDir: '%kernel.cache_dir%'

    App\UnfoldBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'
