services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $mercuryApiBaseUrl: '%bookshelf.mercury_api_base_url%'

    DecentNewsroom\BookshelfBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'

    AsciiDocConverter: ~
