overview:
    path: ''
    controller: DecentNewsroom\UnfoldBundle\Controller\Admin\PublicationAdminController::overview
    methods: [GET]
    defaults: { _unfold_admin: true }

settings:
    path: /settings
    controller: DecentNewsroom\UnfoldBundle\Controller\Admin\PublicationAdminController::settings
    methods: [GET, POST]
    defaults: { _unfold_admin: true }
content:
    path: /content
    controller: DecentNewsroom\UnfoldBundle\Controller\Admin\PublicationAdminController::content
    methods: [GET]
    defaults: { _unfold_admin: true }
about_prepare:
    path: /content/about/prepare
    controller: DecentNewsroom\UnfoldBundle\Controller\Admin\AboutIndexController::prepare
    methods: [POST]
    defaults: { _unfold_admin: true }

about_commit:
    path: /content/about/commit
    controller: DecentNewsroom\UnfoldBundle\Controller\Admin\AboutIndexController::commit
    methods: [POST]
    defaults: { _unfold_admin: true }
category_prepare:
    path: /content/categories/prepare
    controller: DecentNewsroom\UnfoldBundle\Controller\Admin\CategoryIndexController::prepare
    methods: [POST]
    defaults: { _unfold_admin: true }
category_commit:
    path: /content/categories/commit
    controller: DecentNewsroom\UnfoldBundle\Controller\Admin\CategoryIndexController::commit
    methods: [POST]
    defaults: { _unfold_admin: true }
category_content:
    path: /content/category
    controller: DecentNewsroom\UnfoldBundle\Controller\Admin\CategoryContentController::detail
    methods: [GET]
    defaults: { _unfold_admin: true }
category_content_prepare:
    path: /content/category/prepare
    controller: DecentNewsroom\UnfoldBundle\Controller\Admin\CategoryContentController::prepare
    methods: [POST]
    defaults: { _unfold_admin: true }
category_content_commit:
    path: /content/category/commit
    controller: DecentNewsroom\UnfoldBundle\Controller\Admin\CategoryContentController::commit
    methods: [POST]
    defaults: { _unfold_admin: true }
