services:
    _defaults:
        autowire: true
        autoconfigure: true

    DecentNewsroom\UnfoldBundle\:
        resource: '../../src/'
        exclude:
            - '../../src/DependencyInjection/'

    DecentNewsroom\UnfoldBundle\Controller\DiscoveryController:
        tags: ['controller.service_arguments']
